blog/urls.py
from django.urls import path
from blog.views import *

app_name='blog'

urlpatterns=[
    path('',index,name='index'),
    path('profile',profile,name='profile'),
    path('about',about,name='about'),
    path('newpost',newpost,name='newpost'),
    path('login_std',login_std,name='login_std'),
    path('signup_std',signup_std,name='signup_std')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import render

def index(request):
    return render(request,'index.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('blog/', include('blog.urls',namespace = 'blog')),
]

blog/models.py
from django.db import models

# Create your models here.

class login_std(models.Model):
    user=models.CharField(max_length=20)
    password=models.CharField(max_length=16)

class signup_std(models.Model):
    firstname=models.CharField(max_length=20)
    lastname=models.CharField(max_length=20)
    email=models.EmailField(max_length=30)
    contact=models.IntegerField()
    dob=models.DateField()
    user=models.CharField(max_length=20)
    password=models.CharField(max_length=16)

blog/forms.py
from django import forms
from blog.models import login_std,signup_std

class LoginForm(forms.ModelForm):
    class Meta:
        model=login_std
        fields=['user','password']

class SignupForm(forms.ModelForm):
    class Meta:
        model=signup_std
        fields=['firstname','lastname','email','contact','dob','user','password']

blog/views.py
from django.shortcuts import render
from blog.forms import *

# Create your views here.

def index(request):
    return render(request,'blog/index.html')

def profile(request):
    return render(request,'blog/profile.html')

def about(request):
    return render(request,'blog/about.html')

def newpost(request):
    return render(request,'blog/newpost.html')

def login_std(request):
    form=LoginForm()
    context={'form':form}
    return render(request,'blog/login.html',context)

def signup_std(request):
    form=SignupForm()
    context={'form':form}
    return render(request,'blog/signup.html',context)


blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
            Base
        {% endblock title%}
    </title>
</head>
<body>
    <div>
        <div class="head">
            {% block header %}
            {% endblock header %}
        </div>
        <div class="mainnav">
            {% block b1 %}
            {% endblock b1 %}
        </div>
        <div class="footer">
            {% block footer %}
            {% endblock footer %}
        </div>
    </div>
</body>
</html>

blog/templates/blog/about.html
{% extends 'blog/base.html'%}
{% load static%}
{% block title %}
    About
{% endblock title %}
{% block header %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <div class="header">
        <a style="float: left;" href="{% url 'blog:index'%}"><img src="{% }" height="100px" width="100px"></a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:profile'%}">Profile</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:about'%}">About</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:newpost'%}">NewPost</a>
        <a style="margin-left: 55rem;" href="{% url 'blog:login_std'%}">login</a>
        <a href="{% url 'blog:signup_std'%}">signup</a>
    </div>
{% endblock header %}
{%block b1%}
    <h2>About page</h2>
{%endblock b1%}
{%block footer%}
    <div class="footer">
        <h1>Thanks for visiting</h1>
    </div>
{%endblock footer%}

blog/templates/blog/index.html
{% extends 'base.html'%}
{% load static %}
{%block titile%}
    Index
{%endblock titile%}
{%block header%}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <div class="header">
        <a style="float: left;" href="{% url 'blog:index'%}"><img src="{% static 'images/logo.PNG'%}" height="100px" width="100px"></a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:profile'%}">Profile</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:about'%}">About</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:newpost'%}">NewPost</a>
        <a style="margin-left: 55rem;" href="{% url 'blog:login_std'%}">login</a>
        <a href="{% url 'blog:signup_std'%}">signup</a>
    </div>
{%endblock header%}
{%block b1%}
    <div class="main">
        <h4>Main</h4>
    </div>
{%endblock b1%}
{%block footer%}
    <div class="footer">
        <h1>Thanks for visiting</h1>
    </div>
{%endblock footer%}

blog/templates/blog/login.html
{% extends 'base.html'%}
{% load static%}
{% block title %}
    Login
{% endblock title %}
{% block header %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <div class="header">
        <a style="float: left;" href="{% url 'blog:index'%}"><img src="{% static 'images/logo.PNG'%}" height="100px" width="100px"></a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:profile'%}">Profile</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:about'%}">About</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:newpost'%}">NewPost</a>
        <a style="margin-left: 55rem;" href="{% url 'blog:login_std'%}">login</a>
        <a href="{% url 'blog:signup_std'%}">signup</a>
    </div>
{% endblock header %}
{%block b1%}
    <h2>Login Page</h2>
    <form action="">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="submit">
    </form>
{%endblock b1%}
{%block footer%}
    <div class="footer">
        <h1>Thanks for visiting</h1>
    </div>
{%endblock footer%}

blog/templates/blog/newpost.html
{% extends 'base.html'%}
{% load static%}
{% block title %}
    NewPost
{% endblock title %}
{% block header %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <div class="header">
        <a style="float: left;" href="{% url 'blog:index'%}"><img src="{% static 'images/logo.PNG'%}" height="100px" width="100px"></a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:profile'%}">Profile</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:about'%}">About</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:newpost'%}">NewPost</a>
        <a style="margin-left: 55rem;" href="{% url 'blog:login_std'%}">login</a>
        <a href="{% url 'blog:signup_std'%}">signup</a>
    </div>
{% endblock header %}
{%block b1%}
    <h2>NewPost</h2>
{%endblock b1%}
{%block footer%}
    <div class="footer">
        <h1>Thanks for visiting</h1>
    </div>
{%endblock footer%}

blog/templates/blog/profile.html
{% extends 'base.html'%}
{% load static%}
{% block title %}
    Profile
{% endblock title %}
{% block header %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <div class="header">
        <a style="float: left;" href="{% url 'blog:index'%}"><img src="{% static 'images/logo.PNG'%}" height="100px" width="100px"></a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:profile'%}">Profile</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:about'%}">About</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:newpost'%}">NewPost</a>
        <a style="margin-left: 55rem;" href="{% url 'blog:login_std'%}">login</a>
        <a href="{% url 'blog:signup_std'%}">signup</a>
    </div>
{% endblock header %}
{%block b1%}
    <h2>Profile page is created</h2>
{%endblock b1%}
{%block footer%}
    <div class="footer">
        <h1>Thanks for visiting</h1>
    </div>
{%endblock footer%}

blog/templates/blog/signup.html
{% extends 'base.html'%}
{% load static%}
{% block title %}
    Signup
{% endblock title %}
{% block header %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <div class="header">
        <a style="float: left;" href="{% url 'blog:index'%}"><img src="{% static 'images/logo.PNG'%}" height="100px" width="100px"></a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:profile'%}">Profile</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:about'%}">About</a>
        <a style="float: left;margin-top: 25px;" href="{% url 'blog:newpost'%}">NewPost</a>
        <a style="margin-left: 55rem;" href="{% url 'blog:login_std'%}">login</a>
        <a href="{% url 'blog:signup_std'%}">signup</a>
    </div>
{% endblock header %}
{%block b1%}
    <h2>Signup Page</h2>
    <form action="">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="submit">
    </form>
{%endblock b1%}
{%block footer%}
    <div class="footer">
        <h1>Thanks for visiting</h1>
    </div>
{%endblock footer%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            base myblog
        {% endblock title %}
    </title>
</head>
<body>
    {% block header %}
    {% endblock header %}
</body>
</html>

templates/index.html
{% extends 'base.html' %} 
{% block title %}
    myblog
{% endblock title %}
{% block header %}
    <h1>web page</h1>
{% endblock header %}